INFO: localdir at /scratch/1196827.atudisco
INFO: your job will run on local system.
Could not find conda environment: gnn_py10y
You can list all discoverable environments with `conda info --envs`.

# conda environments:
#
base                  *  /home/atudisco/miniconda3
gnn                      /home/atudisco/miniconda3/envs/gnn
gnn_py10                 /home/atudisco/miniconda3/envs/gnn_py10

# conda environments:
#
base                  *  /home/atudisco/miniconda3
gnn                      /home/atudisco/miniconda3/envs/gnn
gnn_py10                 /home/atudisco/miniconda3/envs/gnn_py10

# packages in environment at /home/atudisco/miniconda3:
#
# Name                    Version                   Build  Channel
scikit-learn              1.6.1                    pypi_0    pypi
Running on host: compute-3-25
CUDA Devices: 0,1
Python version: Python 3.9.5
Conda environment: /home/atudisco/miniconda3/bin/python
Installed Python packages:
torch                    2.6.0+cu118
torch-geometric          2.6.1
torchaudio               2.6.0+cu118
torchvision              0.21.0+cu118
scikit-learn             1.6.1
/home/atudisco/miniconda3/lib/python3.9/site-packages/torch_geometric/data/storage.py:452: UserWarning: Unable to accurately infer 'num_nodes' from the attribute set '{'edge_index', 'X', 'y'}'. Please explicitly set 'num_nodes' as an attribute of 'data' to suppress this warning
  warnings.warn(
slurmstepd: error: *** JOB 1196827 ON compute-3-25 CANCELLED AT 2025-05-05T08:41:30 ***
